# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

puts("# ---------------------------Admins-----------------------------------")
Admin.create(name: "Admin")
puts("# ---------------------------Lecturers-----------------------------")
Lecturer.create(name: "Lecturer1")
Lecturer.create(name: "Lecturer2")
puts("# ---------------------------Students-----------------------------")
Student.create(name: "Student1")
Student.create(name: "Student2")
puts("# ---------------------------TeachingAssistants-----------------------------")
TeachingAssistant.create(name: "TA1")
TeachingAssistant.create(name: "TA2")
puts("# --------------------------Courses------------------------------")
Course.create(name:"Course1")
Course.create(name:"Course2")
Course.create(name:"Course3")
puts("# --------------------------DiscussionBoards------------------------------")
DiscussionBoard.create(title:"DiscussionBoard1")
DiscussionBoard.create(title:"DiscussionBoard2")
DiscussionBoard.create(title:"DiscussionBoard3")
puts("# --------------------------Posts------------------------------")
Post.create(content: "Post1")
Post.create(content: "Post2")
Post.create(content: "Post3")
Post.create(content: "Post4")
puts("# --------------------------Replies---------------------------")
Reply.create(content: "Reply1")
Reply.create(content: "Reply2")
Reply.create(content: "Reply3")
Reply.create(content: "Reply4")
Reply.create(content: "Reply5")
puts("# --------------------------Topics------------------------------")
Topic.create(title: "Topic1")
Topic.create(title: "Topic2")
Topic.create(title: "Topic3")
puts("# --------------------------------------------------------")
